export const solutionCatalog = [
  {
    id: 'sol-001',
    slug: 'itfaiye-bilgi-sistemi',
    title: 'İtfaiye Bilgi Sistemi',
    category: 'Kamu Operasyon',
    client: 'Trabzon Büyükşehir Belediyesi',
    period: '2019-2025',
    summary:
      'İhbar, ekip yönetimi, olay takibi ve raporlama süreçlerini tek merkezde birleştiren kurumsal operasyon platformu.',
    modules: ['İhbar Yönetimi', 'Ekip/İstasyon Planlama', 'Canlı Olay Takibi', 'Operasyon Raporlama'],
    outcomes: ['Müdahale koordinasyonunda %32 hızlanma', 'Vardiya planlama hatalarında %26 azalma'],
    highlights: [
      'Saha ekiplerinin mobil veri girişini destekleyen yapı',
      'Yönetim panelinde anlık olay yoğunluğu görünürlüğü',
    ],
  },
  {
    id: 'sol-002',
    slug: 'nolevs-numarataj-levhalama',
    title: 'NOLEVS Numarataj Levhalama Sistemi',
    category: 'Saha Uygulamaları',
    client: 'Kocaeli Büyükşehir Belediyesi',
    period: '2013-2025',
    summary:
      'Adres envanteri, levhalama planı ve saha uygulama adımlarını dijitalleştiren entegre saha yönetim çözümü.',
    modules: ['Adres Envanteri', 'Saha İş Emirleri', 'Levha Takibi', 'Fotoğraf Kanıt Yönetimi'],
    outcomes: ['Saha iş kapanış süresinde %38 iyileşme', 'Adres veri tutarlılığında %41 artış'],
    highlights: [
      'Saha ekipleri için çevrimdışı kullanım desteği',
      'Merkez birimlerde doğrulanabilir uygulama geçmişi',
    ],
  },
  {
    id: 'sol-003',
    slug: 'tasinmaz-kiralama-sistemi',
    title: 'Taşınmaz Kiralama Sistemi',
    category: 'Kurumsal Varlık Yönetimi',
    client: 'Türkiye Büyük Millet Meclisi',
    period: '2025',
    summary:
      'Taşınmaz portföyü, sözleşme süreçleri ve ihale adımlarını şeffaf şekilde yöneten kurumsal yönetim sistemi.',
    modules: ['Portföy Yönetimi', 'Sözleşme Takibi', 'İhale Süreci', 'Gelir Raporlama'],
    outcomes: ['Süreç görünürlüğünde 3 kat artış', 'Evrak döngü süresinde %29 azalma'],
    highlights: [
      'Yetki bazlı erişim ve onay akışları',
      'Yönetim için tek panelde performans raporları',
    ],
  },
  {
    id: 'sol-004',
    slug: 'maks-degisenler-servisi',
    title: 'MAKS Değişenler Servisi',
    category: 'Entegrasyon Servisleri',
    client: 'T.C. Çevre, Şehircilik ve İklim Değişikliği Bakanlığı',
    period: '2025',
    summary:
      'Adres ve numarataj değişimlerini kurum içi sistemlere güvenli biçimde aktaran servis altyapısı.',
    modules: ['Delta Veri Servisi', 'Doğrulama Katmanı', 'Hata Yönetimi', 'İzleme Dashboard'],
    outcomes: ['Veri senkron gecikmesinde %45 azalma', 'Entegrasyon hatalarında %33 düşüş'],
    highlights: ['Kurumsal API sözleşmesiyle uyumlu servisler', 'Yüksek hacimde güvenilir veri akışı'],
  },
  {
    id: 'sol-005',
    slug: 'maks-entegre-numarataj-uygulamasi',
    title: 'MAKS Entegre Numarataj Uygulaması',
    category: 'Coğrafi Bilgi Sistemleri',
    client: 'Bursa Büyükşehir Belediyesi',
    period: '2022-2025',
    summary:
      'Coğrafi altyapı ile numarataj verisini tek platformda birleştirerek kurumlar arası veri uyumu sağlayan çözüm.',
    modules: ['CBS Katman Yönetimi', 'Numarataj Doğrulama', 'Saha Değişiklik Takibi', 'Harita Raporları'],
    outcomes: ['Veri tutarlılığında %40 iyileşme', 'Saha koordinasyonunda %24 hızlanma'],
    highlights: ['Harita tabanlı karar destek ekranları', 'Merkez-saha ekipleri için ortak veri zemini'],
  },
  {
    id: 'sol-006',
    slug: 'enerji-dagitim-saha-koordinasyon-platformu',
    title: 'Enerji Dağıtım Saha Koordinasyon Platformu',
    category: 'Enerji Operasyon',
    client: 'BEDAŞ',
    period: '2025',
    summary:
      'Saha ekipleri, arıza yönetimi ve operasyon izleme süreçlerini birleştiren dağıtım odaklı yönetim çözümü.',
    modules: ['Arıza Akış Yönetimi', 'Saha Ekip Takibi', 'Görev Önceliklendirme', 'Performans Paneli'],
    outcomes: ['Arıza kapanış süresinde %21 düşüş', 'Ekip verimliliğinde %18 artış'],
    highlights: ['Yoğun operasyon dönemlerinde ölçeklenebilir yapı', 'Yönetim katmanı için gerçek zamanlı görünürlük'],
  },
  {
    id: 'sol-007',
    slug: 'trakya-enerji-raporlama-modulu',
    title: 'Trakya Enerji Raporlama Modülü',
    category: 'Analitik ve Raporlama',
    client: 'TREDAŞ',
    period: '2025',
    summary:
      'Dağıtım süreçlerini metriklerle izleyen ve yönetime karar desteği sunan raporlama odaklı modül.',
    modules: ['KPI Paneli', 'Operasyon Analizi', 'Bölgesel Karşılaştırma', 'Rapor Planlama'],
    outcomes: ['Rapor hazırlama süresinde %47 azalma', 'Karar alma hızında %28 artış'],
    highlights: ['Kurum içi birimler için rol bazlı rapor erişimi', 'Trend analizi ile erken aksiyon imkanı'],
  },
  {
    id: 'sol-008',
    slug: 'belediye-cbs-operasyon-merkezi',
    title: 'Belediye CBS Operasyon Merkezi',
    category: 'Coğrafi Operasyon',
    client: 'Antalya Büyükşehir Belediyesi',
    period: '2025',
    summary:
      'CBS verileri üzerinden operasyon birimlerini koordine eden ve saha kararlarını hızlandıran merkezi yönetim paneli.',
    modules: ['Harita Operasyon Merkezi', 'Saha Olay Katmanı', 'Birim Bazlı İzleme', 'Yetki Yönetimi'],
    outcomes: ['Saha koordinasyon süresinde %25 iyileşme', 'Operasyonel görünürlükte belirgin artış'],
    highlights: ['Çok birimli kullanım için ölçekli tasarım', 'Canlı harita odaklı kullanıcı deneyimi'],
  },
  {
    id: 'sol-009',
    slug: 'akilli-basvuru-yonetimi',
    title: 'Akıllı Başvuru Yönetimi',
    category: 'Başvuru Platformları',
    client: 'Gaziosmanpaşa Belediyesi',
    period: '2024-2025',
    summary:
      'Vatandaş başvurularını sınıflandırıp ilgili birimlere otomatik yönlendiren dijital başvuru yönetim çözümü.',
    modules: ['Başvuru Akış Motoru', 'Sınıflandırma Kuralları', 'Birim İş Listeleri', 'Vatandaş Geri Bildirimi'],
    outcomes: ['İlk yanıt süresinde %34 iyileşme', 'Birimler arası devir hatalarında %22 azalma'],
    highlights: ['Vatandaş deneyimi için sade başvuru ekranları', 'Yönetim için izlenebilir süreç raporları'],
  },
  {
    id: 'sol-010',
    slug: 'adres-veri-kalite-platformu',
    title: 'Adres Veri Kalite Platformu',
    category: 'Veri Kalitesi',
    client: 'Büyükçekmece Belediyesi',
    period: '2023-2025',
    summary:
      'Adres kayıtlarında kalite kuralları uygulayarak veri doğruluğunu ve kurum içi entegrasyon kalitesini artıran platform.',
    modules: ['Veri Doğrulama Kuralları', 'Çakışma Analizi', 'Kalite Skoru', 'Düzeltme İş Akışları'],
    outcomes: ['Hatalı kayıt oranında %39 düşüş', 'Veri bakım maliyetinde %27 azalma'],
    highlights: ['Sürekli kalite kontrol yaklaşımı', 'Entegrasyon süreçleriyle uyumlu veri modeli'],
  },
  {
    id: 'sol-011',
    slug: 'belediye-entegrasyon-katmani',
    title: 'Belediye Entegrasyon Katmanı',
    category: 'Kurumsal Entegrasyon',
    client: 'Adana Büyükşehir Belediyesi',
    period: '2023-2025',
    summary:
      'Farklı kurumsal uygulamalar arasında güvenli veri iletişimi sağlayan merkezi entegrasyon katmanı.',
    modules: ['API Gateway', 'Servis Orkestrasyonu', 'Log ve İzleme', 'Hata İzleme'],
    outcomes: ['Entegrasyon geliştirme süresinde %30 iyileşme', 'Sistemler arası tutarlılıkta artış'],
    highlights: ['Merkezi standartlarla düşük operasyon riski', 'Yüksek erişilebilirlik odaklı altyapı'],
  },
  {
    id: 'sol-012',
    slug: 'kurumsal-karar-destek-paneli',
    title: 'Kurumsal Karar Destek Paneli',
    category: 'Yönetim Panelleri',
    client: 'Nilüfer Belediyesi',
    period: '2021-2025',
    summary:
      'Yönetim ekipleri için operasyon metriklerini özetleyen ve stratejik aksiyonları hızlandıran karar destek paneli.',
    modules: ['Yönetici Dashboard', 'Hedef Takibi', 'Trend İzleme', 'Bildirim Altyapısı'],
    outcomes: ['Yönetim rapor döngüsünde %36 kısalma', 'Kritik aksiyon süresinde %23 iyileşme'],
    highlights: ['KPI odaklı sade kullanıcı deneyimi', 'Kurumsal yönetime uygun güvenli erişim modeli'],
  },
]

export const referencePartners = [
  {
    id: 'ref-001',
    name: 'Türkiye Büyük Millet Meclisi',
    period: '2025',
    logo: 'https://noktasal.com.tr/wp-content/uploads/tbmmlogo-150x150.png',
  },
  {
    id: 'ref-002',
    name: 'T.C. Çevre, Şehircilik ve İklim Değişikliği Bakanlığı',
    period: '2025',
    logo: 'https://noktasal.com.tr/wp-content/uploads/cevre-sehircilik-iklim-200x150.jpg',
  },
  {
    id: 'ref-003',
    name: 'BEDAŞ - Boğaziçi Elektrik Dağıtım A.Ş.',
    period: '2025',
    logo: 'https://noktasal.com.tr/wp-content/uploads/bogazicick-150x150.jpg',
  },
  {
    id: 'ref-004',
    name: 'Kocaeli Büyükşehir Belediyesi',
    period: '2013-2025',
    logo: 'https://noktasal.com.tr/wp-content/uploads/kbblogonew-170x140.jpg',
  },
  { id: 'ref-005', name: 'Trabzon Büyükşehir Belediyesi', period: '2019-2025' },
  { id: 'ref-006', name: 'Bursa Büyükşehir Belediyesi', period: '2022-2025' },
  { id: 'ref-007', name: 'TREDAŞ - Trakya Elektrik Dağıtım A.Ş.', period: '2025' },
  { id: 'ref-008', name: 'AEDAŞ - Akdeniz Elektrik Dağıtım A.Ş.', period: '2025' },
  { id: 'ref-009', name: 'ÇEDAŞ - Çamlıbel Elektrik Dağıtım A.Ş.', period: '2025' },
  { id: 'ref-010', name: 'Antalya Büyükşehir Belediyesi', period: '2025' },
  { id: 'ref-011', name: 'Adana Büyükşehir Belediyesi', period: '2023-2025' },
  { id: 'ref-012', name: 'Şanlıurfa Büyükşehir Belediyesi', period: '2020-2025' },
  { id: 'ref-013', name: 'Gaziosmanpaşa Belediyesi', period: '2024-2025' },
  { id: 'ref-014', name: 'Büyükçekmece Belediyesi', period: '2023-2025' },
  { id: 'ref-015', name: 'Nilüfer Belediyesi', period: '2021-2025' },
  { id: 'ref-016', name: 'İstanbul Büyükşehir Belediyesi', period: '2015-2016' },
  { id: 'ref-017', name: 'Ordu Büyükşehir Belediyesi', period: '2015-2023' },
]
